# Air 配置文件 (.air.toml) - 优化版
# 自动重载Go应用，解决热重载时 exit code 1 的问题

# 工作目录
root = "."
tmp_dir = "tmp"

[build]
# 编译命令 - 添加了更多编译选项
cmd = "go build -ldflags='-s -w' -o ./tmp/main ./cmd/main.go"

# 二进制文件名
bin = "tmp/main"

# 执行命令 - 优化版本，包含更好的信号处理
full_bin = "./tmp/main"

# 预构建和后构建钩子
pre_cmd = ["echo 'Starting build...'"]
post_cmd = ["echo 'Build completed.'"]

# 监听的文件扩展名
include_ext = ["go", "html", "yaml", "yml", "toml"]

# 忽略目录 - 添加了更多忽略项以减少不必要的重载
exclude_dir = [
    "tmp",
    ".git",
    "node_modules",
    "logs",
    "vendor",
    "static/node_modules",
    "static/dist",
    ".idea",
    ".vscode",
    "bin"
]

# 监听目录
include_dir = []

# 排除特定文件
exclude_file = [
    "*.log",
    "*.pid",
    "*.lock",
    "*.tmp"
]

# 延迟时间 - 增加延迟以避免频繁重载
delay = 3000 # ms (从2秒增加到3秒)

# 构建错误时是否停止 - 改为 false 以提高稳定性
stop_on_error = false

# 发生构建错误时发送中断信号
send_interrupt = true

# 杀死延迟时间 - 给应用更多时间优雅关闭
kill_delay = 2000 # ms

# 重新运行延迟
rerun_delay = 1000 # ms

# air日志文件
log = "air.log"

[log]
# 显示日志时间
time = true
# 显示主颜色
main_only = false

[color]
# 自定义颜色
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
app = "white"

[misc]
# 退出时清理tmp目录
clean_on_exit = true

[screen]
# 清屏
clear_on_rebuild = true
# 保留应用输出
keep_scroll = false