# Server 配置
server:
  port: 8081
  mode: debug # debug, release, test
  read_timeout: 60
  write_timeout: 60
  idle_timeout: 60
  enable_rate_limit: true # 是否启用全局限流
  rate_limit: 100 # 每秒最大请求数
  rate_burst: 200 # 突发情况下允许的最大请求数

# 日志配置
log:
  level: debug # debug, info, warn, error, fatal, panic
  filename: logs/app.log
  max_size: 100 # MB
  max_backups: 10
  max_age: 30 # days
  compress: true
  format: json # json, text

# 数据库配置
database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: password
  dbname: test
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600 # seconds

# Redis配置
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10

# JWT配置
jwt:
  secret: "your-secret-key"
  expire: 24 # hours
  issuer: "go-framework"

# 模板配置
template:
  path: ./templates
  layouts: ./templates/layouts
  extension: .html

# 静态文件配置
static:
  path: ./static/dist

# Gzip压缩配置
gzip:
  enabled: true # 是否启用gzip压缩
  level: 6 # 压缩级别 (1-9, 1最快, 9最高压缩比) 

# Session配置
session:
  store: cookie # cookie, redis
  name: go_session
  secret: "session-secret-key"
  max_age: 60 # 分钟
  secure: false
  http_only: true
  path: /
  domain: ""
  same_site: lax # lax, strict, none